name: "Lanta Camera Proxy"
version: "1.7.0"
slug: "lanta-cam-proxy"
description: "Прокси-сервер камер видеонаблюдения LanTa с автоматическим обновлением токенов"
url: "https://github.com/amatsnev/hass-addon-lanta-cam"
arch:
  - amd64
  - aarch64
startup: services
init: false
ports:
  8199/tcp: 8199
ports_description:
  8199/tcp: "Web UI / HLS stream proxy"
options:
  login: ""
  password: ""
  refresh_interval: 5400
schema:
  login: str
  password: str
  refresh_interval: int
panel_icon: mdi:cctv
startup: services
